# Generated by Django 4.2.1 on 2023-06-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CookieSessionApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="BCaccount",),
    ]
